INSERT INTO city_weather_date_list(weather_id,
                                   city_id,
                                   date,
                                   daytime_enum,
                                   nighttime_enum,
                                   max_degrees,
                                   min_degrees,
                                   precipitation,
                                   humidity,
                                   wind_speed)
VALUES ('cb04d223-769f-4d00-809e-f7431c6592f1',
        9390,
        '2023-05-17',
        'SOL'::daytime_enum,
        'LIMPA'::nighttime_enum,
        30,
        8,
        0,
        33,
        10);
INSERT INTO city_weather_date_list(weather_id,
                                   city_id,
                                   date,
                                   daytime_enum,
                                   nighttime_enum,
                                   max_degrees,
                                   min_degrees,
                                   precipitation,
                                   humidity,
                                   wind_speed)
VALUES ('9e5e2ed3-b371-4767-aa00-0974968779e5',
        7777,
        '2023-05-17',
        'SOL'::daytime_enum,
        'LIMPA'::nighttime_enum,
        30,
        8,
        0,
        33,
        10);